story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home url
    path('', include('story7app.urls', namespace='story7app')),
    path('story8/', include('story8app.urls', namespace='story8app')),
    path('story9/', include('story9app.urls', namespace='story9app')),
]

story7app/urls.py
from django.urls import path
from . import views

app_name = 'story7app'

urlpatterns = [
    path('', views.story7app, name='story7app'),
]

story8app/urls.py
from django.urls import path
from . import views

app_name = 'story8app'

urlpatterns = [
    path('', views.story8app, name='story8app'),
]

story9app/urls.py
from django.urls import path
from . import views

app_name = 'story9app'

urlpatterns = [
    path('', views.story9app, name='story9app'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

story7app/models.py
from django.db import models

# Create your models here.

story8app/models.py
from django.db import models

# Create your models here.

story9app/models.py
from django.db import models

# Create your models here.

story8app/forms.py
from django import forms
# from django.forms import widgets

# class SearchForm(forms.Form):
#     search_query = forms.CharField(max_length = 50)

story7app/views.py
from django.shortcuts import render

# Create your views here.
def story7app(request):
    return render(request, 'index.html')

story8app/views.py
from django.shortcuts import render
from . import forms

# Create your views here.
def story8app(request):
    return render(request, 'story8/index.html')

story9app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages

# Create your views here.

def story9app(request):
    return render(request, 'story9/index.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if username and email and password1 and password2:
            if "@" in username:
                messages.info(request, "Username can't contain @ in it")
                return redirect('/story9/register')

            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already taken")
                if User.objects.filter(email=email).exists():
                    messages.info(request, 'Email already used')
                    if password1 != password2:
                        messages.info(request, "Password didn't match.")
                        return redirect('/story9/register')
                    else:
                        messages.info(request, "Please log in")
                        return redirect('/story9/login')
                else:
                    messages.info(request, "Please log in")
                    return redirect('/story9/login')
                    
            else:
                # print("Password did't match") 
                user = User.objects.create_user(username=username, email=email, password=password1)
                user.save()
                # print('User Created')
                user = auth.authenticate(username=username, password=password1)
                # messages.info(request, 'User Created')
                auth.login(request, user)
                return redirect('/story9/')
        else:
            messages.info(request, "Please fill the form first.")
            return redirect('/story9/register')

    else:
        return render(request, 'story9/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if("@" in username):
            user = auth.authenticate(email=username, password=password)
        else:
            user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/story9/')
        else:
            messages.info(request, 'Invalid information')
            return redirect('/story9/login')

    else:
        return render(request, 'story9/login.html')

def logout(request):
    auth.logout(request)
    request.session.flush()
    return redirect('/story9/')

story7app/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- <link rel='stylesheet'  type="text/css" href="{% static 'accounts/style2.css' %}" id="theme_css"> -->
    <link rel='stylesheet' type="text/css" id = "theme" href="{% static 'css/dark.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Oswald&display=swap" rel="stylesheet">

    <link 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js" 
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" 
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <title>Story 7</title>
</head>

<body>

    <div class = "hi">
        <h1 name="hicolor">HELLO AGAIN</h1>
        <div id="hitransparent">
            <h1>CLICK ON ITEMS BELOW</h1> 
        </div>
        <p>i've spent 4 hours copying some code</p>
        <div>
            <button type="button" name="button" id="buttonID"> Change theme </button>
        </div>
    </div>

        
    <ul class="accordion">
        
        <li>
            <a>About Me</a>
            <p>I’m a full-time student with a high passion in web design and front-end development. I’m currently studying Information System in Faculty of Computer Science of University of Indonesia. I have confidence in giving a reliable service to those who’s in need of a clean looking website. Please kindly look around the page to see if I’m a good candidate for your next project.
            </p>
        </li>
        <li>
            <a>Activity</a>
            <p>College<br>
                PMB 2019<br>
                BEM Fasilkom 2019<br>
                Music
            </p>
        </li>

        <li>
            <a>Hobby</a>
            <p>Graphic Design<br>
                Front-end Development<br>
                UI/UX<br>
                Beatmaking
        </li>

        <li>
            <a>Achievement</a>
            <p>Nothing<br>
                404<br>
        </li>
    </ul>

    <script src="{% static 'script/script.js' %}">
    </script>

</body>
</html>

story8app/templates/story8/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- <link rel='stylesheet'  type="text/css" href="{% static 'accounts/style2.css' %}" id="theme_css"> -->
    <link rel='stylesheet' type="text/css" id = "theme" href="{% static 'css/dark.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Oswald&display=swap" rel="stylesheet">

    <link 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js" 
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" 
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <title>Story 8</title>
</head>

{% block content %}
{% endblock %}
<script src="{% static 'script/script.js' %}">
</script>
</html>

story8app/templates/story8/index.html
{% extends "story8/base.html" %}

{% block content %}
<body>

    <div class = "hi">
        <h1 name="hicolor">KNOWLEDGE</h1>
        <div id="hitransparent">
            <h1>WOW KNOWLEDGE</h1> 
        </div>
        <p>search for your KNOWLEDGE here</p>
    </div>

    <div style = "height: 2vw"></div>

    <div class = "row">
        <div style = "margin-left: 2vw"></div>
        <input type="text" id = "searchbox" placeholder=" Search here">
        <input type="submit" class="button" id = "submit" value = "Search"></button>
        <div style = "width: 2vw;"></div>
        <p style = "font-size: 1.1vw; color: #AAA">You can click on titles to go to Play Book links</p>
    </div>

    <div style = "height: 2vw"></div>

    <div style = "display: flex; flex-direction: row;">
        <table id = "book_container" style="width:100%">
        </table>
    </div>

</body>
{% endblock %}

story9app/templates/story9/base.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- <link rel='stylesheet'  type="text/css" href="{% static 'accounts/style2.css' %}" id="theme_css"> -->
    <link rel='stylesheet' type="text/css" id = "theme" href="{% static 'css/dark.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Oswald&display=swap" rel="stylesheet">

    <link 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js" 
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" 
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <title>{% block title %}Story 9{% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>
</html>

story9app/templates/story9/index.html
{% extends "story9/base.html" %}

{% block title %}Story 9 | Login{% endblock %}

{% block content %}
    <div class = "hi">
        <h1 name="hicolor">HEY THERE</h1>
        {% if user.is_authenticated %}
        <div id="hitransparent">
            <h1 id="username_show">{{ user.username }}</h1> 
            <a class="button_class noback" name="loggy" href="{% url 'story9app:logout' %}">Log Out</a>
        </div>
        {% else %}
        <div id="hitransparent">
            <h1 id="username_show">STRANGER</h1>
        </div>
        <p>idk who the f you are</p>
        <a class="button_class noback" href="{% url 'story9app:login' %}">Log In</a> 
        {% endif %}
    </div>
{% endblock %}

story9app/templates/story9/login.html
{% extends "story9/base.html" %}

{% block content %}
<body>
    <div class = "hi">
        <div id="hitransparent">
            <h1>WELCOME</h1> 
        </div>
        <p>remind me who you are</p>
    </div>

    <div style = "height: 2vw"></div>

    <div class = "column">
        <form class = "regform" action="login" method="POST">
            {% csrf_token %}
            <input type="text" name="username" id="username" placeholder="Username or Email"><br>
            <input type="password" name="password" id="password" placeholder="Password"><br>
            <div style = "height: 1vw"></div>
            <input id="buttonID" type="Submit" value="Login">
            <!-- {{ form }}
            <input type="Submit" value="Sign Up"> -->
            <a class="button_class noback" id="register" href="{% url 'story9app:register' %}">I don't have an account</a>
        </form>
        
    </div>

    <div class = "messages">
        <p>
        {% for message in messages %}
        {{ message }}<br>
        {% endfor %}
        </p>
    </div>
</body>
{% endblock %}

story9app/templates/story9/register.html
{% extends "story9/base.html" %}

{% block title %}Story 9 | Register{% endblock %}

{% block content %}
<body>
    <div class = "hi">
        <div id="hitransparent">
            <h1>WELCOME</h1> 
        </div>
        <p>let's get to know eachother</p>
    </div>

    <div style = "height: 2vw"></div>

    <div class = "column">
        <form class = "regform" action="register" method="POST">
            {% csrf_token %}
            <input type="text" name="username" id="username" placeholder="User Name"><br>
            <input type="email" name="email" id="email" placeholder="Your Email"><br>
            <input type="password" name="password1" id="password1" placeholder="Password"><br>
            <input type="password" name="password2" id="password2" placeholder="Confirm Password"><br>
            <div style = "height: 1vw"></div>
            <input id="buttonID" type="Submit" value="Register">
            <a class="button_class noback" id="login" href="{% url 'story9app:login' %}">I already have an account</a>
        </form>
    </div>

    <div class = "messages">
        <p>
        {% for message in messages %}
        {{ message }}<br>
        {% endfor %}
        </p>
    </div>
</body>
{% endblock %}